name: Trigger Property in Radius

on:
  schedule:
    # (see https://crontab.guru)
    - cron: '0 */24 * * *'
jobs:
  build:
    name: Trigger Cron Job
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X POST -d {} https://jituproperty.com/api/Job/propertyInRadius_Daily
